### ISSUE TITLE
Auto-invite issues

### ISSUE THREAD

**Issue by blacelle** [Snocean/ProEnchanters#10]
- Auto-invite may invite ourselves: this is irrlevant
- Auto-invite can easily invite other enchants. 
  - Could `LFW` excluded ?
  - Could one customize the matching expression?

**Comment by Snocean** [comment]
The Filters and Triggers area in the addon are specifically what this is for, please see https://www.wowhead.com/classic/guide/gold-making-guide-with-enchanting-and-the-pro-enchanters-add-on-23583#triggers-and-filters-settings for some extra information

tl;dr - You can add lfw (must be all lower case) to the filtered words so that players who are 'enchanter LFW' will get filtered out from being invited, you can also add players names directly incase their advertising message doesn't contain a viable filtered word, add their names the same way it is viewed in-game (Capital letter for first letter, rest small letters)

Feel free to also join the discord if you'd like some more help

**Comment by blacelle** [comment]
Is it possible to auto-invite from whispers?

**Comment by Snocean** [comment]
The whisper auto invites you can setup in the triggers and filters as well,
by default I believe “!inv” is setup so that when you advertise your
services you can include “whisper me !inv” so people can self invite to
your party
